name: CI Pipeline

on:
  push:
    branches:
      - main
      - reg
      - hyper

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run regression script
      run: |
        if [ -f regression.py ]; then python regression.py; fi
        if [ -f hyperparameter_tuning.py ]; then python hyperparameter_tuning.py; fi
